# Generated by Django 6.1 on 2026-08-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_alter_drawing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='author',
            field=models.CharField(max_length=80, verbose_name='Автор'),
        ),
    ]
