# Generated by Django 6.1 on 2026-08-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0010_drawing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Отклонено'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Причина отклонения'),
        ),
    ]
